services:
  - type: web
    name: identity-reconciliation
    env: docker
    region: singapore
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: ""    # Dockerfile handles build
    startCommand: ""    # Dockerfile handles start
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
